/* remainder.asm
 *
 * Programmer: Mayer Goldberg, 2010
 */

 REMAINDER:
  PUSH(FP);
  MOV(FP, SP);

  PUSH(R1);

  CMP(FPARG(1), IMM(2));
  JUMP_EQ(REMAINDER_ARGS_AMOUNT_OK);

  // ERROR - ARG AMOUNT

 REMAINDER_ARGS_AMOUNT_OK:
  MOV(R0,FPARG(2));
  CMP(IND(R0), T_INTEGER);
  JUMP_EQ(REMAINDER_1ST_ARG_TYPE_OK);

  // ERROR FIRST IS NOT INT

 REMAINDER_1ST_ARG_TYPE_OK:
  MOV(R1,FPARG(3));
  CMP(IND(R1), T_INTEGER);
  JUMP_EQ(REMAINDER_2ND_ARG_TYPE_OK);

  // ERROR SECOND IS NOT INT

 REMAINDER_2ND_ARG_TYPE_OK:
  MOV(R0,INDD(R0,1));
  MOV(R1,INDD(R1,1));
  REM(R0,R1);
  PUSH(R0);
  CALL(MAKE_SOB_INTEGER);
  DROP(1);

  POP(R1);

  POP(FP);
  RETURN;
