/* vector.asm
 *
 * Programmers: Amitai Degani, Tal Zelig, 2014
 */


 VECTOR_CONSTRUCTOR:
  PUSH(FP);
  MOV(FP,SP);

  //PUSH(R1);
  //PUSH(R2);

  MOV(R1,IMM(2));
  MOV(R2,FPARG(1));
  INCR(R2);

 VECTOR_CONSTRUCTOR_ARG_LOOP:
  CMP(R1,R2);
  JUMP_GT(VECTOR_CONSTRUCTOR_ARG_LOOP_EXIT);
  PUSH(FPARG(R1));
  INCR(R1);
  JUMP(VECTOR_CONSTRUCTOR_ARG_LOOP);

VECTOR_CONSTRUCTOR_ARG_LOOP_EXIT:
  MOV(R1,FPARG(1));
  PUSH(R1);
  CALL(MAKE_SOB_VECTOR);
  ADD(R1,1);
  DROP(R1);

  //POP(R2);
  //POP(R1);

  POP(FP);
  RETURN;
