/* vector.asm
 *
 * Programmers: Amitai Degani, Tal Zelig, 2014
 */


 VECTOR_CONSTRUCTOR:
  PUSH(FP);
  MOV(FP,SP);
  PUSH(R1);
  MOV(R1,FPARG(1));
  ADD(R1,1);

 VECTOR_CONSTRUCTOR_ARG_LOOP:
  CMP(R1,1);
  JUMP_LE(VECTOR_CONSTRUCTOR_ARG_LOOP_EXIT);
  PUSH(FPARG(R1));
  DECR(R1);
  JUMP(VECTOR_CONSTRUCTOR_ARG_LOOP);

VECTOR_CONSTRUCTOR_ARG_LOOP_EXIT:
  MOV(R1,FPARG(1));
  PUSH(R1);
  CALL(MAKE_SOB_VECTOR);
  DROP(R1);
  POP(R1);
  POP(FP);
  RETURN;
